export interface Movie {
  id: number;
  title: string;
  description: string;
  poster_url?: string;
  release_date: string;
  rating: number;
  genres: string[];
}

export interface TVShow {
  id: number;
  name: string;
  description: string;
  poster_url?: string;
  first_air_date: string;
  rating: number;
  genres: string[];
}

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: "The Matrix",
    description: "A computer hacker learns from mysterious rebels about the true nature of his reality.",
    poster_url: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    release_date: "1999-03-31",
    rating: 8.7,
    genres: ["Action", "Sci-Fi"],
  },
  {
    id: 2,
    title: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing technology.",
    poster_url: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    release_date: "2010-07-16",
    rating: 8.8,
    genres: ["Action", "Sci-Fi", "Thriller"],
  },
  {
    id: 3,
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc on Gotham.",
    poster_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-18",
    rating: 9.0,
    genres: ["Action", "Crime", "Drama"],
  },
  {
    id: 4,
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, and a gangster intertwine.",
    poster_url: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-10-14",
    rating: 8.9,
    genres: ["Crime", "Drama"],
  },
  {
    id: 5,
    title: "Forrest Gump",
    description: "The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man.",
    poster_url: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-07-06",
    rating: 8.8,
    genres: ["Drama", "Romance"],
  },
  {
    id: 6,
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and redemption.",
    poster_url: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    rating: 9.3,
    genres: ["Drama"],
  },
  {
    id: 7,
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space to ensure humanity's survival.",
    poster_url: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-07",
    rating: 8.6,
    genres: ["Adventure", "Drama", "Sci-Fi"],
  },
  {
    id: 8,
    title: "The Godfather",
    description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
    poster_url: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-24",
    rating: 9.2,
    genres: ["Crime", "Drama"],
  },
  {
    id: 9,
    title: "Parasite",
    description: "A poor family schemes to become employed by a wealthy family.",
    poster_url: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    rating: 8.6,
    genres: ["Comedy", "Drama", "Thriller"],
  },
  {
    id: 10,
    title: "Spirited Away",
    description: "A young girl enters a world ruled by gods, witches, and spirits.",
    poster_url: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    rating: 8.6,
    genres: ["Animation", "Adventure", "Fantasy"],
  },
  {
    id: 11,
    title: "Gladiator",
    description: "A former Roman General sets out to exact vengeance against the corrupt emperor.",
    poster_url: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    release_date: "2000-05-05",
    rating: 8.5,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 12,
    title: "The Prestige",
    description: "Two stage magicians engage in competitive one-upmanship in Victorian London.",
    poster_url: "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8G8A0JN.jpg",
    release_date: "2006-10-20",
    rating: 8.5,
    genres: ["Drama", "Mystery", "Thriller"],
  },
  {
    id: 13,
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cutthroat music conservatory.",
    poster_url: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    release_date: "2014-10-10",
    rating: 8.5,
    genres: ["Drama", "Music"],
  },
  {
    id: 14,
    title: "Dune",
    description: "A noble family becomes embroiled in a war for control of the galaxy's most valuable asset.",
    poster_url: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    rating: 8.0,
    genres: ["Adventure", "Action", "Sci-Fi"],
  },
  {
    id: 15,
    title: "Avengers: Endgame",
    description: "The Avengers assemble once more to reverse Thanos' actions and restore balance.",
    poster_url: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    release_date: "2019-04-26",
    rating: 8.4,
    genres: ["Action", "Adventure", "Sci-Fi"],
  },
  {
    id: 16,
    title: "Everything Everywhere All at Once",
    description: "An aging Chinese immigrant is swept up in an insane adventure across the multiverse.",
    poster_url: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    release_date: "2022-03-25",
    rating: 8.3,
    genres: ["Action", "Adventure", "Sci-Fi"],
  },
  {
    id: 17,
    title: "Oppenheimer",
    description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb.",
    poster_url: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-21",
    rating: 8.4,
    genres: ["Biography", "Drama", "History"],
  },
  {
    id: 18,
    title: "The Silence of the Lambs",
    description: "A young FBI cadet must confide in an incarcerated cannibal to catch another serial killer.",
    poster_url: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    release_date: "1991-02-14",
    rating: 8.6,
    genres: ["Crime", "Drama", "Thriller"],
  },
  {
    id: 19,
    title: "The Lion King",
    description: "Lion prince Simba flees his kingdom after his father's tragic death.",
    poster_url: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    release_date: "1994-06-24",
    rating: 8.5,
    genres: ["Animation", "Adventure", "Drama"],
  },
  {
    id: 20,
    title: "Joker",
    description: "A mentally troubled comedian descends into insanity and becomes the Joker.",
    poster_url: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    release_date: "2019-10-04",
    rating: 8.4,
    genres: ["Crime", "Drama", "Thriller"],
  },
];

export const mockTVShows: TVShow[] = [
  {
    id: 1,
    name: "Breaking Bad",
    description: "A high school chemistry teacher turned methamphetamine producer.",
    poster_url: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    first_air_date: "2008-01-20",
    rating: 9.5,
    genres: ["Crime", "Drama", "Thriller"],
  },
  {
    id: 2,
    name: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery.",
    poster_url: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    first_air_date: "2016-07-15",
    rating: 8.7,
    genres: ["Drama", "Fantasy", "Horror"],
  },
  {
    id: 3,
    name: "Game of Thrones",
    description: "Nine noble families fight for control over Westeros.",
    poster_url: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    first_air_date: "2011-04-17",
    rating: 9.3,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 4,
    name: "The Office",
    description: "A mockumentary on a group of typical office workers.",
    poster_url: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    first_air_date: "2005-03-24",
    rating: 9.0,
    genres: ["Comedy"],
  },
  {
    id: 5,
    name: "The Last of Us",
    description: "A survivor and a young girl navigate a post-apocalyptic world.",
    poster_url: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    first_air_date: "2023-01-15",
    rating: 8.9,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 6,
    name: "The Crown",
    description: "Follows the political rivalries and romance of Queen Elizabeth II's reign.",
    poster_url: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
    first_air_date: "2016-11-04",
    rating: 8.6,
    genres: ["Biography", "Drama", "History"],
  },
  {
    id: 7,
    name: "The Mandalorian",
    description: "A lone bounty hunter travels the outer reaches of the galaxy.",
    poster_url: "https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    first_air_date: "2019-11-12",
    rating: 8.7,
    genres: ["Action", "Adventure", "Sci-Fi"],
  },
  {
    id: 8,
    name: "The Witcher",
    description: "Geralt of Rivia, a monster hunter, struggles to find his place in a world.",
    poster_url: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    first_air_date: "2019-12-20",
    rating: 8.2,
    genres: ["Action", "Adventure", "Fantasy"],
  },
  {
    id: 9,
    name: "Sherlock",
    description: "A modern update finds the famous detective and his doctor solving crime in 21st century London.",
    poster_url: "https://image.tmdb.org/t/p/w500/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
    first_air_date: "2010-07-25",
    rating: 9.1,
    genres: ["Crime", "Drama", "Mystery"],
  },
  {
    id: 10,
    name: "Friends",
    description: "Follows the personal and professional lives of six friends living in Manhattan.",
    poster_url: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    first_air_date: "1994-09-22",
    rating: 8.9,
    genres: ["Comedy", "Romance"],
  },
  {
    id: 11,
    name: "The Wire",
    description: "The Baltimore drug scene through the eyes of drug dealers and law enforcement.",
    poster_url: "https://image.tmdb.org/t/p/w500/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
    first_air_date: "2002-06-02",
    rating: 9.3,
    genres: ["Crime", "Drama", "Thriller"],
  },
  {
    id: 12,
    name: "Black Mirror",
    description: "An anthology series exploring a twisted, high-tech multiverse.",
    poster_url: "https://image.tmdb.org/t/p/w500/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg",
    first_air_date: "2011-12-04",
    rating: 8.8,
    genres: ["Drama", "Sci-Fi", "Thriller"],
  },
  {
    id: 13,
    name: "Westworld",
    description: "A theme park populated by artificial beings where visitors can do whatever they want.",
    poster_url: "https://image.tmdb.org/t/p/w500/y5f36PegkD5rkP8yLHqWPJlekUo.jpg",
    first_air_date: "2016-10-02",
    rating: 8.5,
    genres: ["Drama", "Mystery", "Sci-Fi"],
  },
  {
    id: 14,
    name: "House of the Dragon",
    description: "The Targaryen civil war known as the Dance of the Dragons.",
    poster_url: "https://image.tmdb.org/t/p/w500/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    first_air_date: "2022-08-21",
    rating: 8.4,
    genres: ["Action", "Adventure", "Drama"],
  },
  {
    id: 15,
    name: "Better Call Saul",
    description: "The transformation of Jimmy McGill into criminal lawyer Saul Goodman.",
    poster_url: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    first_air_date: "2015-02-08",
    rating: 9.0,
    genres: ["Crime", "Drama"],
  },
  {
    id: 16,
    name: "The Boys",
    description: "A group of vigilantes set out to take down corrupt superheroes.",
    poster_url: "https://image.tmdb.org/t/p/w500/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg",
    first_air_date: "2019-07-26",
    rating: 8.7,
    genres: ["Action", "Comedy", "Crime"],
  },
  {
    id: 17,
    name: "True Detective",
    description: "Police investigations uncover personal and professional secrets of those involved.",
    poster_url: "https://image.tmdb.org/t/p/w500/aowr4xpLP5sRCL50TkuADomJ3Fs.jpg",
    first_air_date: "2014-01-12",
    rating: 8.9,
    genres: ["Crime", "Drama", "Mystery"],
  },
  {
    id: 18,
    name: "The Sopranos",
    description: "A New Jersey mob boss seeks help from a psychiatrist.",
    poster_url: "https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg",
    first_air_date: "1999-01-10",
    rating: 9.2,
    genres: ["Crime", "Drama"],
  },
  {
    id: 19,
    name: "Succession",
    description: "The Roy family fights for control of their media and entertainment empire.",
    poster_url: "https://image.tmdb.org/t/p/w500/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
    first_air_date: "2018-06-03",
    rating: 8.9,
    genres: ["Drama"],
  },
  {
    id: 20,
    name: "The Handmaid's Tale",
    description: "A woman forced into sexual servitude struggles to survive in a totalitarian society.",
    poster_url: "https://image.tmdb.org/t/p/w500/tFTJ3yRvlEPpSuL3BMgog7KFdWz.jpg",
    first_air_date: "2017-04-26",
    rating: 8.4,
    genres: ["Drama", "Sci-Fi", "Thriller"],
  },
];
